---
title: "CS2: utterance proposer evals"
output: github_document
---




```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(brms)
library(tidyboot)
library(cspplot)
library(faintr)
```

Read data:
```{r}
path = "../data/cs2-utterance-proposer/results_20_SAGE_cs2-utterance-proposer-evals_full.csv"
d <- read_csv(path)
# exclude prolific info
#d %>% select(-prolific_pid, -prolific_study_id, -prolific_session_id) %>% write_csv(path)
```

Check attention check performance:
```{r}
d_preprocessed <- d %>%
  mutate(
    correct_answer = as.numeric(correct_answer),
    lower_bound = as.numeric(lower_bound),
    upper_bound = as.numeric(upper_bound),
    p1 = as.numeric(p1),
    p2 = as.numeric(p2),
    p3 = as.numeric(p3)
  )

fillers <- d_preprocessed %>% filter(trial_type == "filler") %>%
  rowwise() %>%
  mutate(
    is_correct = as.numeric(abs(correct_answer - lower_bound) < 6 &
                          abs(correct_answer - upper_bound) < 6 &
                          abs(correct_answer - p1) < 6 &
                          abs(correct_answer - p2) < 6 &
                          abs(correct_answer - p3) < 6
                          )
         )
# attention check passing rate
sum(fillers$is_correct) / nrow(fillers)
bad_subjects <- fillers %>% filter(is_correct == 0) %>%
  pull(submission_id) %>% unique()
```

Analyse main trials:
```{r}
main_trials <- d_preprocessed %>%
  filter(trial_type == "main") %>%
#  filter(!(submission_id %in% bad_subjects)) %>%
  select(submission_id, lower_bound, p1, p2, p3, state_type, trialNr, upper_bound, vignette) %>%
  pivot_longer(
    cols = c(p1, p2, p3), names_to = "proposal_nr", values_to = "proposal"
  ) 

main_trials_long <- main_trials %>%
  pivot_longer(cols = c(upper_bound, lower_bound, proposal), names_to = "condition", values_to = "rating") %>%
  mutate(condition = factor(condition, levels = c("lower_bound", "proposal", "upper_bound"), labels = c("lower bound", "proposals", "upper bound")),
         state_type = factor(state_type, levels = c("s_typical", "s_atypical"), labels = c("typical state", "atypical state")))

main_trials_summary <- main_trials_long %>%
  group_by(condition) %>%
  tidyboot_mean(
    column = rating
  )

main_trials_long %>%
  ggplot(., aes(x = condition, y = rating, color = condition)) +
  geom_point(alpha=0.3, position=position_jitter(0.2)) +
  geom_point(data = main_trials_summary, aes(x = condition, y = mean, color = condition), size=4) +
  geom_errorbar(data = main_trials_summary, aes(x = condition, y = mean, ymin=ci_lower, ymax=ci_upper, color = condition), width=0.4) +
  theme_csp()
```

Now group these by state type (typical vs atypical):
```{r}
main_trials_summary_byState <- main_trials_long %>%
  group_by(state_type, condition) %>%
  tidyboot_mean(
    column = rating
  )

main_trials_long %>%
  ggplot(., aes(x = condition, y = rating, color = condition)) +
  geom_point(alpha=0.3, position=position_jitter(0.2)) +
  geom_point(data = main_trials_summary_byState, aes(x = condition, y = mean, color = condition), size=4, alpha = 1.5) +
  geom_errorbar(data = main_trials_summary_byState, aes(x = condition, y = mean, ymin=ci_lower, ymax=ci_upper, color = condition), width=0.4, size = 1.2) +
  facet_grid(.~state_type) +
  theme_csp()

#ggsave("figs/cs2-proposer-results.png", width=7, height=5)
```

```{r}
contrasts(main_trials_long$condition)
main_trials_long_rm <- main_trials_long %>%  
  mutate(condition = factor(condition, levels = c("proposals", "lower bound", "upper bound")))

rm_cs2_utt <- brm(
  rating ~ condition + (1 + condition | vignette) + (1 + condition | submission_id),
  data = main_trials_long_rm,
  iter = 4000,
  cores = 4,
  control = list(adapt_delta=0.95)
)
summary(rm_cs2_utt)
```

```{r}
contrasts(main_trials_long$state_type)

rm_cs2_utt_byState <- brm(
  rating ~ condition * state_type + (1 + condition * state_type | vignette) + (1 + condition*state_type | submission_id),
  data = main_trials_long,
  iter = 4000,
  cores = 4,
  control = list(adapt_delta = 0.95)
)
summary(rm_cs2_utt_byState)
```

Check if the upper bound was judged higher than the proposals, and lower bound was judged lower than the proposals, in each state condition:
```{r}
compare_groups(
  rm_cs2_utt_byState,
  higher = condition == "upper bound" & state_type == "typical state",
  lower = condition == "proposals" & state_type == "typical state"
)

compare_groups(
  rm_cs2_utt_byState,
  higher = condition == "proposals" & state_type == "typical state",
  lower = condition == "lower bound" & state_type == "typical state"
)

compare_groups(
  rm_cs2_utt_byState,
  higher = condition == "upper bound" & state_type == "atypical state",
  lower = condition == "proposals" & state_type == "atypical state"
)

compare_groups(
  rm_cs2_utt_byState,
  higher = condition == "proposals" & state_type == "atypical state",
  lower = condition == "upper bound" & state_type == "atypical state"
)

compare_groups(
  rm_cs2_utt_byState,
  higher = condition == "proposals" & state_type == "atypical state",
  lower = condition == "lower bound" & state_type == "atypical state"
)

compare_groups(
  rm_cs2_utt_byState,
  higher = condition == "lower bound" & state_type == "atypical state",
  lower = condition == "upper bound" & state_type == "atypical state"
)
```